In [24]:
# Introduction

In [25]:
print("Hello world")
print('Fit model with', 11, 'variables')


Hello world
Fit model with 11 variables


In [26]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [27]:
# Dealing with python lists
x=[3, 4, 5]
x

[3, 4, 5]

In [28]:
y=[4, 9, 7]
x+y

[3, 4, 5, 4, 9, 7]

In [29]:
# Introduction to numpy
import numpy as np
x=np.array([3, 4, 5])
y=np.array([4, 9, 7])
x+y

array([ 7, 13, 12])

In [30]:
# Matrices are represented as 2 dimensional arrays, and vectors are represented as one dimensional arrays. 
x=np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# Find out about the attributes of a variable/list use x.attribute where attribute is replaced with the attribute name that you want to learn about. 
x.ndim
x.dtype

dtype('int64')

In [32]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [33]:
np.array([[1, 2, 3], [4, 5, 6]], float).dtype

dtype('float64')

In [34]:
x=np.array([1, 2, 3, 4, 5])
x.sum()

np.int64(15)

In [35]:
x=np.array([1, 2, 3, 4, 5])
np.sum(x)

np.int64(15)

In [36]:
# Using reshape function
x=np.array([1, 2, 3, 4, 5, 6])
print("beginning x:\n", x)
x_reshape=x.reshape((2, 3))
print("reshaped x: \n", x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x: 
 [[1 2 3]
 [4 5 6]]


In [ ]:
# How to access certain elements in an array
x_reshape[0,0]

np.int64(1)

In [38]:
x[2]

np.int64(3)

In [39]:
# How to generate random data
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [42]:
x=np.random.normal(size=50)
x

array([-0.35108185,  0.79877398,  0.46522369, -1.25446975, -0.29898085,
       -1.87847745, -1.79890384, -1.85490314, -0.28329577,  0.78811528,
       -0.04214535,  0.02167659, -0.68556395,  0.02734711,  0.41433201,
       -0.09204714, -0.24377317, -0.63708093, -0.1691243 ,  0.6725208 ,
       -1.09632956,  0.63451931, -1.71571093, -1.5956964 , -0.61425852,
        1.63805071, -1.17721145,  0.88943885,  0.64536185, -0.37217136,
        1.37630833, -0.2687569 , -0.72583181,  0.59729745, -1.44190838,
        0.01501074, -1.02698257,  0.07057738, -0.31648785,  0.05588853,
       -1.7372597 , -0.04153979,  0.02876949,  2.22281408, -1.9124607 ,
        1.06421254,  0.71797259, -1.60796054,  0.32790642,  1.07330909])

In [46]:
y= x+np.random.normal(loc=50, scale=1, size=50)
y
np.corrcoef(x, y)

array([[1.        , 0.69214411],
       [0.69214411, 1.        ]])

In [47]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

[1.17282575 3.8436567 ]
[-11.606713     6.69869985]


In [ ]:
rng=np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))

Generator(PCG64)
